inherit_from: .rubocop_todo.yml

AllCops:
  # Only enforce rules that have an entry in the style guide
  StyleGuideCopsOnly: true
  Exclude:
    - 'mediawiki/**/*'
    - 'mediawiki-*/**/*'
    - 'puppet/modules/cdh/**/*'
    - 'puppet/modules/mariadb/**/*'
    - 'puppet/modules/nginx/**/*'
    - 'puppet/modules/stdlib/**/*'
    - 'puppet/modules/wikimetrics/**/*'
    - 'puppet/modules/wmflib/**/*'
    - 'tmp/**/*'
    - 'Vagrantfile-extra.rb'
    - 'vendor/**/*'

# Please enable this when this offense is fixed
#Metrics/LineLength:
#  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/SignalException:
  Enabled: false

# Pick one and stay consistent
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  ExactNameMatch: true
